### ISSUE TITLE
TypeError: astWindow is null

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#943]
https://sentry.io/canadian-digital-service/vac-benefits-directory/issues/651108153/

```
TypeError: astWindow is null
  at None (moz-extension://51122017-c44d-4809-b0f3-1167d3b2357d/toolbar.js:60:8)
  at fBound (moz-extension://51122017-c44d-4809-b0f3-1167d3b2357d/toolbar.js:18:15)
  at o (/_next/static/commons/main-b94eb50edc12c91aefe5.js:1:802311)
```

**Comment by maxneuvians** [comment]
I think this is an extension bug vs. bug on our app

**Comment by maxneuvians** [comment]
Retried in Browserstack - no issue. @apmcguigan is checking on his windows desktop

<img width="1552" alt="screen shot 2018-08-21 at 11 12 55 am" src="https://user-images.githubusercontent.com/867334/44410842-3ff90680-a533-11e8-9877-38bdcee79451.png">

**Comment by apmcguigan** [comment]
Works on Firefox for me, browser console gives me the following: 

```
C:\Program Files (x86)\Mozilla Firefox\defaults\pref\autoconfig.js:1: prefs parse error: unexpected character
Bootstrapped manifest not allowed to use 'resource' directive. chrome.manifest:1
Bootstrapped manifest not allowed to use 'resource' directive. chrome.manifest:7
Bootstrapped manifest not allowed to use 'resource' directive. chrome.manifest:2
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More] fgtauth
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xul
The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature. success.txt
unreachable code after return statement main-3a0fdc09783e5e7e694b.js:1:865791

1534863742804	Toolkit.Telemetry	WARN	TelemetryStorage::_scanArchive - have seen this id before: a22bfdd2-5d7e-4345-955d-f958817b9ebb, overwrite: false
1534863835055	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 120"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:120
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:130
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:309
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:241
1534863835061	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 120"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:120
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:130
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:309
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:241
1534863835094	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 120"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:120
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:130
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:309
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:241
1534863835138	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 120"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:120
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:130
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:309
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:241
1534863835143	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 120"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:120
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:130
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:309
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:241
1534863835148	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 120"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:120
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:130
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:309
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:241
1534863835157	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 120"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:120
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:130
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:309
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:241
1534863835185	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 120"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:120
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:130
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:309
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:241

unreachable code after return statement main-3a0fdc09783e5e7e694b.js:1:865791
The resource at “https://www.google-analytics.com/analytics.js” was blocked because tracking protection is enabled.[Learn More] benefits-directory
Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”. benefits-directory:1
Loading failed for the <script> with source “https://maps.googleapis.com/maps-api-v3/api/js/34/1a/common.js”. benefits-directory:1
Loading failed for the <script> with source “https://maps.googleapis.com/maps-api-v3/api/js/34/1a/stats.js”. benefits-directory:1
Loading failed for the <script> with source “https://maps.googleapis.com/maps-api-v3/api/js/34/1a/util.js”. benefits-directory:1
unreachable code after return statement main-3a0fdc09783e5e7e694b.js:1:865791
Use of nsIFile in content process is deprecated. NetUtil.jsm:302:12
unreachable code after return statement main-3a0fdc09783e5e7e694b.js:1:865791
```
